### PR TITLE
Add some IP tools

### PR DESCRIPTION
**Pull request by qti3e**
Hi
I made some new functions for managing IP addresses and block specific IP address
Here is list of functions:
1. getUserIP($user)  //will return an array 
2. checkIP($ip) //Check if an ip address is blocked or not
3. blockIP($ip) //block ip
4. blockUser($user) //block user
5. unblockIP($ip) //unblock ip

### CODE REVIEW

**Comment by Xaraknid** [comment]
Nice tools you have there.  Some tought on the subject.

What happens if the user you block is in public area with other legit users in the same public area ( hospital / work / cofee shop ).  They will all be banned and disconnected in the same time and will not be able connect back without ever knowing why because you close the connection at handshake, unfortunately there is no way to collect the http error status on client side.

**Comment by Qti3e** [comment]
I can add a timer and unblock user after for example 5 min
Is it good or you have a better idea?

**Comment by Qti3e** [comment]
Fixed :)

**Comment by Xaraknid** [comment]
There are 2 part in my previous post : 

1- Because you loop over all active connection and ban&close every connection with same IP.  You can end up disconnecting a whole school/cofee shop etc using your application because they share the same IP over internet.  If you are fine with that I do not mind.

2-  I guess that you will send a message that you ban the user before closing is connection.  Because when he try to reconnect he will never see the HTTP error status 403.  The workaround the websocket restriction is to let him complete the handshake then you can check IP and if is banned send him a message and then close the connection.  It all depend why and on what purpose you want to ban the user.  Also it depend if you want to let know the person you ban him and any other person sharing is IP.

**Comment by Qti3e** [comment]
Oh, yes I'll fix it too
just a moment please

**Comment by Qti3e** [comment]
About second option It's for other programmers that are using this library and it's they're work to say their clients that we blocked you in their own way

**Comment by Qti3e** [comment]
Is it a dead project?

**Comment by Xaraknid** [comment]
I don't think it's dead. The last update are 2 months old he is working on development branch to implement various thing.

**Comment by ghedipunk** [comment]
This project is not dead.

My email inbox, however, is overfull and swamped with spam, so I've missed the emails notifying me of this pull request, and saw the latest response only by accident.  Sorry for not responding earlier.

I'll review this and add functionality.  Thank you!

**Comment by Qti3e** [comment]
It's one month!

**Comment by Qti3e** [comment]
It's more than 2 months

**Comment by lyoussefl** [comment]
hey i added something to the code first for using it in a chat app if you want to have two persons communicate in private and every one has his own id so to get out of ip problems you have to be connected and u get the id from database anyway who wants the code tell me and i added too something to let the server reads the data of the ip only not the messages so who needs the code contact me

**Pull request closed without merging**
